/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocorporacionglobito;

import javax.swing.JOptionPane;
import logica.Global;
import logica.Vendedora;

/**
 *
 * @author Gloriana
 */
public class frmEntrega extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEntrega
     */
    public frmEntrega() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdentificacion = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblEntegaPedidos = new javax.swing.JLabel();
        bntBuscar = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblTotalCantidad = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Entrega de pedidos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/printed5.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        lblNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEntegaPedidos.setText("Identificación de vendedora:");

        bntBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/magnifying46.png"))); // NOI18N
        bntBuscar.setText("Buscar");
        bntBuscar.setFocusable(false);
        bntBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });

        btnEntregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/drawing4.png"))); // NOI18N
        btnEntregar.setText("Entregar pedido");
        btnEntregar.setFocusable(false);
        btnEntregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VENDEDORA", "PERFUME", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        jLabel9.setText("Totales");

        lblTotalCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEntegaPedidos)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(bntBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntregar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(lblTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bntBuscar, btnEntregar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntregar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEntegaPedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bntBuscar, btnEntregar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        try {
            int id = Integer.parseInt(txtIdentificacion.getText());
            Vendedora vendedora = Global.listaVendedora.buscarVendedora(id);
            if (vendedora == null) {
                limpiarTabla();
                JOptionPane.showMessageDialog(rootPane, "Vendedora no existe!!!", "Vendedora",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                lblNombre.setText(vendedora.getNombre());
                tblPedidos.setModel(Global.listaPedido.imprimirTabla(id));
                int total = 0;
                double totalPedido = 0.0;
                for (int i = 0; i < tblPedidos.getRowCount(); i++) {
                    total += Integer.parseInt(tblPedidos.getValueAt(i, 2).toString());
                    totalPedido += Double.parseDouble(tblPedidos.getValueAt(i, 4).toString());
                }
                lblTotalCantidad.setText("" + total);
                lblTotal.setText("" + totalPedido);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "El id de la vendedora debe ser un numero", "Vendedora",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        try {
            int id = Integer.parseInt(txtIdentificacion.getText());
            Vendedora vendedora = Global.listaVendedora.buscarVendedora(id);
            if (vendedora != null) {
                Global.listaPedido.entregarPedido(id);
                Global.listaPedido.escribirPedidos();
                Global.listaEntrega.escribirEntregas();
                limpiarTabla();
                txtIdentificacion.setText("");
                JOptionPane.showMessageDialog(rootPane, "Pedido entregado exitosamente!!!", "Entrega",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vendedora no existe!!!", "Vendedora",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException exc) {
            JOptionPane.showMessageDialog(rootPane, "El id de la vendedora debe ser un numero", "Vendedora",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEntregarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // cargar 
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEntegaPedidos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalCantidad;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtIdentificacion;
    // End of variables declaration//GEN-END:variables

    private void limpiarTabla() {
        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Vendedora", "Perfume", "Cantidad", "Precio", "Total"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        lblNombre.setText("");
        lblTotal.setText("");
        lblTotalCantidad.setText("");
    }
}
