/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocorporacionglobito;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import logica.Global;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.watermark.SubstanceImageWatermark;

/**
 *
 * @author Gloriana
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        SubstanceLookAndFeel.setCurrentWatermark(new SubstanceImageWatermark(this.getClass().getResourceAsStream("/Imagenes/fondo.jpg")));
        
        //cargar los archivos con la informacion previamente almacenada
        Global.listaPerfume.leerPerfumes();
        Global.listaVendedora.leerVendedoras();
        Global.listaPedido.leerPedidos();
        Global.listaEntrega.leerEntregas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnPerfume = new javax.swing.JButton();
        btnVendedora = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnEntregaPedidos = new javax.swing.JButton();
        btnReportesPedidos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuArchivoPerfume = new javax.swing.JMenuItem();
        mnuArchivoVendedora = new javax.swing.JMenuItem();
        mnuArchivoPedido = new javax.swing.JMenuItem();
        mnuArchivoEntregaPedido = new javax.swing.JMenuItem();
        mnuArchivoReportePedido = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuArchivoSalir = new javax.swing.JMenuItem();
        mnuVentana = new javax.swing.JMenu();
        mnuVentanaParalelo = new javax.swing.JMenuItem();
        mnuVentanaCascada = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuVentanaCerrar = new javax.swing.JMenuItem();
        mnuVentanaCerrarTodas = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAyudaContenido = new javax.swing.JMenuItem();
        mnuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Corporación Globito");
        setIconImage(getIconImage());

        jToolBar1.setRollover(true);

        btnPerfume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wiping11.png"))); // NOI18N
        btnPerfume.setText("Perfumes");
        btnPerfume.setFocusable(false);
        btnPerfume.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPerfume.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfumeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPerfume);

        btnVendedora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business59.png"))); // NOI18N
        btnVendedora.setText("Vendedoras");
        btnVendedora.setFocusable(false);
        btnVendedora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVendedora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVendedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedoraActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVendedora);

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verification5.png"))); // NOI18N
        btnPedido.setText("Pedidos");
        btnPedido.setFocusable(false);
        btnPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPedido);

        btnEntregaPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/printed5.png"))); // NOI18N
        btnEntregaPedidos.setText("Entrega");
        btnEntregaPedidos.setFocusable(false);
        btnEntregaPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntregaPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntregaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregaPedidosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEntregaPedidos);

        btnReportesPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/global12.png"))); // NOI18N
        btnReportesPedidos.setText("Reporte entregas");
        btnReportesPedidos.setFocusable(false);
        btnReportesPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportesPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportesPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesPedidosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReportesPedidos);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel3.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/global12.png"))); // NOI18N
        btnReporte.setText("Reporte");
        btnReporte.setFocusable(false);
        btnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReporte);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mnuArchivoPerfume.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuArchivoPerfume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wiping11.png"))); // NOI18N
        mnuArchivoPerfume.setText("Perfumes");
        mnuArchivo.add(mnuArchivoPerfume);

        mnuArchivoVendedora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mnuArchivoVendedora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business59.png"))); // NOI18N
        mnuArchivoVendedora.setText("Vendedoras");
        mnuArchivoVendedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoVendedoraActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoVendedora);

        mnuArchivoPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuArchivoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verification5.png"))); // NOI18N
        mnuArchivoPedido.setText("Pedidos");
        mnuArchivoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoPedidoActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoPedido);

        mnuArchivoEntregaPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuArchivoEntregaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/printed5.png"))); // NOI18N
        mnuArchivoEntregaPedido.setText("Entrega");
        mnuArchivo.add(mnuArchivoEntregaPedido);

        mnuArchivoReportePedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuArchivoReportePedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/global12.png"))); // NOI18N
        mnuArchivoReportePedido.setText("Reporte entrega");
        mnuArchivo.add(mnuArchivoReportePedido);
        mnuArchivo.add(jSeparator1);

        mnuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuArchivoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout13.png"))); // NOI18N
        mnuArchivoSalir.setText("Salir");
        mnuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoSalir);

        jMenuBar1.add(mnuArchivo);

        mnuVentana.setText("Ventana");

        mnuVentanaParalelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuVentanaParalelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parallel.png"))); // NOI18N
        mnuVentanaParalelo.setText("En paralelo");
        mnuVentanaParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentanaParaleloActionPerformed(evt);
            }
        });
        mnuVentana.add(mnuVentanaParalelo);

        mnuVentanaCascada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuVentanaCascada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cascade.png"))); // NOI18N
        mnuVentanaCascada.setText("En cascada");
        mnuVentanaCascada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentanaCascadaActionPerformed(evt);
            }
        });
        mnuVentana.add(mnuVentanaCascada);
        mnuVentana.add(jSeparator2);

        mnuVentanaCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mnuVentanaCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        mnuVentanaCerrar.setText("Cerra actual");
        mnuVentanaCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentanaCerrarActionPerformed(evt);
            }
        });
        mnuVentana.add(mnuVentanaCerrar);

        mnuVentanaCerrarTodas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        mnuVentanaCerrarTodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_all.png"))); // NOI18N
        mnuVentanaCerrarTodas.setText("Cerrar todas");
        mnuVentanaCerrarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentanaCerrarTodasActionPerformed(evt);
            }
        });
        mnuVentana.add(mnuVentanaCerrarTodas);

        jMenuBar1.add(mnuVentana);

        mnuAyuda.setText("Ayuda");

        mnuAyudaContenido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuAyudaContenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help.png"))); // NOI18N
        mnuAyudaContenido.setText("Contenido...");
        mnuAyudaContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaContenidoActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAyudaContenido);

        mnuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/about.png"))); // NOI18N
        mnuAcercaDe.setText("Acerca de...");
        mnuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAcercaDe);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArchivoVendedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoVendedoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuArchivoVendedoraActionPerformed

    private void mnuArchivoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoPedidoActionPerformed

    }//GEN-LAST:event_mnuArchivoPedidoActionPerformed

    private void mnuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoSalirActionPerformed
        btnSalirActionPerformed(evt);
    }//GEN-LAST:event_mnuArchivoSalirActionPerformed

    private void mnuVentanaParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentanaParaleloActionPerformed
        int x = (int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth());
        int y = (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight());
        JInternalFrame objetos[] = escritorio.getAllFrames();
        if (objetos.length > 0) {
            int ancho = x / objetos.length;
            int largo = x / objetos.length;
            x = y = 0;
            for (JInternalFrame v : objetos) {
                v.setSize(ancho, largo);
                v.setLocation(x, y);
                x += ancho;
            }
        }
    }//GEN-LAST:event_mnuVentanaParaleloActionPerformed

    private void btnPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfumeActionPerformed
        frmPerfume perfume = new frmPerfume();
        if (!esAbierta(perfume.getClass())) {
            perfume.setSize(600, 425);
            perfume.show();
            centrar(perfume);
            escritorio.add(perfume);
            try {
                perfume.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.out.println(ex.toString());
            }
        } else {

        }

    }//GEN-LAST:event_btnPerfumeActionPerformed

    private void btnVendedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedoraActionPerformed
        frmVendedora perfume = new frmVendedora();
        if (!esAbierta(perfume.getClass())) {
            perfume.setSize(600, 425);
            perfume.show();
            centrar(perfume);
            escritorio.add(perfume);
            try {
                perfume.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.out.println(ex.toString());
            }
        } else {

        }
    }//GEN-LAST:event_btnVendedoraActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        frmPedido perfume = new frmPedido();
        if (!esAbierta(perfume.getClass())) {
            perfume.setSize(600, 425);
            perfume.show();
            centrar(perfume);
            escritorio.add(perfume);
            try {
                perfume.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.out.println(ex.toString());
            }
        } else {

        }
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnEntregaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregaPedidosActionPerformed
        frmEntrega perfume = new frmEntrega();
        if (!esAbierta(perfume.getClass())) {
            perfume.setSize(600, 425);
            perfume.show();
            centrar(perfume);
            escritorio.add(perfume);
            try {
                perfume.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.out.println(ex.toString());
            }
        } else {
            perfume = null;
        }
    }//GEN-LAST:event_btnEntregaPedidosActionPerformed

    private void btnReportesPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesPedidosActionPerformed
        frmReporteEntrega perfume = new frmReporteEntrega();
        if (!esAbierta(perfume.getClass())) {
            perfume.setSize(600, 425);
            perfume.show();
            centrar(perfume);
            escritorio.add(perfume);
            try {
                perfume.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.out.println(ex.toString());
            }
        } else {

        }
    }//GEN-LAST:event_btnReportesPedidosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respu = JOptionPane.showConfirmDialog(rootPane,
                "Realmente desea salir?", "Salir",
                JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respu == JOptionPane.YES_OPTION) {
            System.exit(1);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mnuAyudaContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaContenidoActionPerformed
        try {
            File path = new File("Manual de usuario.pdf");
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch(IllegalArgumentException ex){
            JOptionPane.showMessageDialog(rootPane, "Error al intentar acceder al manual de usuario",
                    "Ayuda",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuAyudaContenidoActionPerformed

    private void mnuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaDeActionPerformed
        final frmAboutMe dialog = new frmAboutMe(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                dialog.dispose();
            }
        });
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_mnuAcercaDeActionPerformed

    private void mnuVentanaCerrarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentanaCerrarTodasActionPerformed
        JInternalFrame objetos[] = escritorio.getAllFrames();
        for (JInternalFrame v : objetos) {
            v.dispose();
        }
    }//GEN-LAST:event_mnuVentanaCerrarTodasActionPerformed

    private void mnuVentanaCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentanaCerrarActionPerformed
        try {
            JInternalFrame v = escritorio.getSelectedFrame();
            v.dispose();
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_mnuVentanaCerrarActionPerformed

    private void mnuVentanaCascadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentanaCascadaActionPerformed
        int xOffset = 30, yOffset = 30;
        JInternalFrame objetos[] = escritorio.getAllFrames();
        for (JInternalFrame v : objetos) {
            v.setLocation(xOffset += 25, yOffset += 30);
            try {
                v.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuVentanaCascadaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        frmReportes perfume = new frmReportes();
        escritorio.add(perfume);
        perfume.setVisible(true);
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame.setDefaultLookAndFeelDecorated(true); //que nos permite dejar a Substance la decoracion ( por asi decirlo)
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistAquaSkin"); // Setencia que aplica el skin Creme de Substance    
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregaPedidos;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnPerfume;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnReportesPedidos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVendedora;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuArchivoEntregaPedido;
    private javax.swing.JMenuItem mnuArchivoPedido;
    private javax.swing.JMenuItem mnuArchivoPerfume;
    private javax.swing.JMenuItem mnuArchivoReportePedido;
    private javax.swing.JMenuItem mnuArchivoSalir;
    private javax.swing.JMenuItem mnuArchivoVendedora;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuAyudaContenido;
    private javax.swing.JMenu mnuVentana;
    private javax.swing.JMenuItem mnuVentanaCascada;
    private javax.swing.JMenuItem mnuVentanaCerrar;
    private javax.swing.JMenuItem mnuVentanaCerrarTodas;
    private javax.swing.JMenuItem mnuVentanaParalelo;
    // End of variables declaration//GEN-END:variables
@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/ballon.png"));
        return retValue;
    }

    private boolean esAbierta(Object ventana) {
        boolean abierta = false;
        JInternalFrame objetos[] = escritorio.getAllFrames();

        for (JInternalFrame v : objetos) {
            if (v.getClass().equals(ventana)) {
                abierta = true;
                JOptionPane.showMessageDialog(rootPane, "Ventana ya esta abierta", "Abrir ventana", JOptionPane.ERROR_MESSAGE);
                try {
                    v.setSelected(true);
                } catch (PropertyVetoException ex) {
                    System.out.println(ex.toString());
                }
                break;
            }
        }
        return abierta;
    }

    public void centrar(JInternalFrame ventana) {
        int x = (int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth() / 2 - ventana.getWidth() / 2);
        int y = (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() / 2 - ventana.getHeight() / 2);
        ventana.setLocation(x, 0);
    }

}
