/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocorporacionglobito;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Global;
import logica.Vendedora;

/**
 *
 * @author Admin01
 */
public class frmReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReportes
     */
    public frmReportes() {
        initComponents();
        // paso 1
        Global.listaVendedora.leerVendedoras(); //carga las vendedoras, seria el arraylist

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        btnGenero = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICACION", "NOMBRE", "SEXO"
            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        btnGenero.setText("Cantidad Genero");
        btnGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar)
                        .addGap(33, 33, 33)
                        .addComponent(btnGenero)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // paso 2
        String nombre = txtNombre.getText().toUpperCase(); //obtiene el valor del txt
        //se obtiene de  public TableModel imprimirTabla() en lista Vendedora
        String etiquetas[] = new String[]{"IDENTIFICACION", "NOMBRE", "SEXO"};
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                etiquetas) {
            boolean[] canEdit = new boolean[3];

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        String fila[] = new String[3];
        for (Vendedora vendedora : Global.listaVendedora.getListVendedora()) {
            if (vendedora.getNombre().startsWith(nombre)) { // filtra el nombre segun el txt
                fila[0] = "" + vendedora.getIdentificacion();
                fila[1] = vendedora.getNombre();
                fila[2] = "" + vendedora.getSexo();
                modelo.addRow(fila);
            }
        }
        tblReporte.setModel(modelo);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneroActionPerformed
        String nombre = txtNombre.getText().toUpperCase(); //obtiene el valor del txt
        int mujer = 0;
        int hombre = 0;
        for (Vendedora vendedora : Global.listaVendedora.getListVendedora()) {
            if (vendedora.getNombre().startsWith(nombre)) { // filtra el nombre segun el txt
                if (vendedora.getSexo().startsWith("M")) {
                    mujer++;
                } else {
                    hombre++;
                }
            }
        }
        JOptionPane.showMessageDialog(rootPane, "La cantidad de mujeres es: " 
                + mujer+"\n" +"La cantidad de hombres es: " + hombre);
    }//GEN-LAST:event_btnGeneroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReporte;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
